bind: "0.0.0.0:8001"
timeout_ms: 2000
cache_secs: 5

targets:
  - name: nginx
    host: 127.0.0.1
    port: 80
    http_path: "/"
    expect_status: [200,301,302]
    present:
      type: systemd
    version: "1.18.0-6ubuntu14.7" 

  - name: bind9
    host: 127.0.0.1
    port: 53
    present:
      type: systemd
    version: "1:9.18.39-0ubuntu0.22.04.2"

  - name: kea
    host: 127.0.0.1
    port: 8000
    present:
      type: systemd
    version: "2.2.0-1ubuntu0.2" 

  - name: jenkins
    host: 127.0.0.1
    port: 8080
    http_path: "/login"
    expect_status: [200,403]
    present:
      type: http

  - name: nats_mgmt
    host: 127.0.0.1
    port: 8222
    http_path: "/healthz"
    expect_status: [200]
    present:
      type: http

  - name: nats_client
    host: 127.0.0.1
    port: 4222
    present:
      type: tcp

  - name: grafana
    host: 127.0.0.1
    port: 3000
    http_path: "/api/health"
    expect_status: [200]
    present:
      type: http

  - name: prometheus
    host: 127.0.0.1
    port: 9090
    http_path: "/-/ready"
    expect_status: [200]
    present:
      type: http

  - name: loki
    host: 127.0.0.1
    port: 3100
    http_path: "/ready"
    expect_status: [200]
    present:
      type: http
